- hosts: localhost
  gather_facts: false
  vars:
    docker_network: demo-kind-yelb_yelb-network
  collections:
    - community.docker
  tasks:
    - name: "get network info"
      docker_network_info:
        name: "{{ docker_network }}"
      register: net_info
    - debug:
        msg: "{{ net_info }}"

    - name: "get container info"
      docker_container_info:
        name: "{{ item }}"
      register: container_info
      loop: "{{ net_info.network.Containers.keys() }}"

    - debug:
        msg: "{{ item }}"
      loop: "{{ container_info.results|json_query('[].container') }}"

    - name: copy the output to a local file
      copy:
        content: "{{ container_info.results }}"
        dest: "ansible_data.json"
      delegate_to: localhost

    - name: execute install script
      script: parse_docker.py



